### ISSUE TITLE
DriveFusion ?

### ISSUE THREAD

**Issue by bncbnc** [google/google-drive-proxy#2]
It says this project is currently in use by the DriveFusion project.

I can not find anywhere what exactly this DriveFusion project is.

Can a link be provided to guide me in the right direction?

Thanks!

**Comment by fcoulombegoogle** [comment]
Hi,

Drive Fusion is in the process of being released. We're just going through
the last few corporate processes and waiting for approval.
I will send a message to this issue whenever it gets released.

cheers
Francois

**Comment by Phsenaux** [comment]
Hi Francois,
I'm also interested in the DriveFusion project to test the operation of Drive.proxy.
Thanks for send me a message when it gets released.

**Comment by jpgaribotti** [comment]
Drive Fusion has been renamed "Google Drive Shell Extension". We have now released it, and you can view it at https://github.com/google/google-drive-shell-extension.
